<a href="https://colab.research.google.com/github/ywang1110/Deep-Learning/blob/main/Neural_Networks_and_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Course source:**
https://www.coursera.org/learn/neural-networks-deep-learning/home/welcome <br>
**Lecturer:** Andrew Ng

Broadcasting in Python
----

In [ ]:
import numpy as np
A=np.random.randint(10, size=(3,4))
print(A)

[[4 7 9 9]
 [7 8 5 9]
 [8 6 2 7]]


In [ ]:
cal=A.sum(axis=0) 
cal.shape

(4,)

In [7]:
# (3,4)/(1,4)matrix Python would copy (1,4)matirx 3 times and it turns into (3,4)matix
percentage=A/cal.reshape(1,4)*100   
percentage

array([[21.05263158, 33.33333333, 56.25      , 36.        ],
       [36.84210526, 38.0952381 , 31.25      , 36.        ],
       [42.10526316, 28.57142857, 12.5       , 28.        ]])